### PR TITLE
Pixel418 => Elephant418 rename

### PR DESCRIPTION
**Pull request by nike-17**

### CODE REVIEW

**Comment by tzi** [comment]
Thanks!

Do you use Staq?
On which project?

Cheers,
Thomas.

**Comment by nike-17** [comment]
HI Tomas.
I saw it at phpWeekly mail list.
just started to review it.
First thing that i mention was that link to travis was broken so i decided to fix it.

**Comment by tzi** [comment]
OK.
Any feedback are welcome ;)

**Comment by tzi** [comment]
We use this version in production, so it's maintained.
We started to cut this framework in libraries to improve the documentation and the adoption.
But it takes time :)

**Pull request merged**
